// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinav.Repository.Contexts;

#nullable disable

namespace Sinav.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sinav.Core.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("IndirimOrani")
                        .HasColumnType("float");

                    b.Property<int>("SanatciId")
                        .HasColumnType("int");

                    b.Property<bool>("SatisDurum")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SanatciId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumAdi = "Deneme1",
                            CikisTarihi = new DateTime(2025, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8523),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8509),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 1,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AlbumAdi = "Deneme2",
                            CikisTarihi = new DateTime(2024, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8538),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8537),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 2,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AlbumAdi = "Deneme3",
                            CikisTarihi = new DateTime(2033, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8541),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8540),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 3,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AlbumAdi = "Deneme4",
                            CikisTarihi = new DateTime(2030, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8543),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8543),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 4,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AlbumAdi = "Deneme5",
                            CikisTarihi = new DateTime(2035, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8546),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8545),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 5,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AlbumAdi = "Deneme6",
                            CikisTarihi = new DateTime(2031, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8548),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8547),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 6,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            AlbumAdi = "Deneme7",
                            CikisTarihi = new DateTime(2026, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8550),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8549),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 1,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AlbumAdi = "Deneme8",
                            CikisTarihi = new DateTime(2027, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8552),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8552),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 2,
                            SatisDurum = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AlbumAdi = "Deneme9",
                            CikisTarihi = new DateTime(2028, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8554),
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 888, DateTimeKind.Local).AddTicks(8554),
                            Fiyat = 150m,
                            IndirimOrani = 15.0,
                            SanatciId = 1,
                            SatisDurum = true,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Sinav.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(1072),
                            FirstName = "Sefa",
                            LastName = "Attila",
                            Password = "C8B7388EE2A0BC141591C0DF7644134EC65504D1E15F3A18719302BF66332E03",
                            Status = 0,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Sinav.Core.Entities.Sanatci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sanatcis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(2894),
                            FirstName = "Ali",
                            LastName = "Gündüz",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(2900),
                            FirstName = "Mehmet",
                            LastName = "Uzun",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(2901),
                            FirstName = "Veli",
                            LastName = "Kısa",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(2902),
                            FirstName = "Adnan",
                            LastName = "Ziya",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(2903),
                            FirstName = "Fatih",
                            LastName = "Aslan",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 9, 11, 15, 11, 20, 889, DateTimeKind.Local).AddTicks(2905),
                            FirstName = "Furkan",
                            LastName = "Kartal",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Sinav.Core.Entities.Album", b =>
                {
                    b.HasOne("Sinav.Core.Entities.Sanatci", "Sanatci")
                        .WithMany("Albums")
                        .HasForeignKey("SanatciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanatci");
                });

            modelBuilder.Entity("Sinav.Core.Entities.Sanatci", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
